# Generated by Selenium IDE
require "selenium-webdriver"
require "json"
describe "Fw" do
  before(:each) do
    portNumber = "8921"
    driverPath = "/Users/amandeep/Downloads/farm-bot/chromedriver"
    options = Selenium::WebDriver::Chrome::Options.new(debugger_address: "localhost:#{portNumber}", binary: '/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome')

    Selenium::WebDriver::Chrome::Service.driver_path = driverPath
    #File.join(Dir.pwd, 'chromedriver') //relative path

    #options.add_emulation(user_agent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36')
    options.add_argument("--headless")
    options.add_argument("--disable-extensions")
    options.add_argument("--disable-web-security")
    options.add_argument("--allow-running-insecure-content")

    @driver = Selenium::WebDriver.for(:chrome, options: options)
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it "fw" do
    time = Time.now
    formattedTime = time.strftime("%m-%d-%Y.%H.%M.%S")
    @driver.manage.window.resize_to(1920, 1080)
    @driver.get("https://play.farmersworld.io//")

    @driver.session_storage.clear
    @driver.local_storage.clear

    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, "label").text == "Rpc Endpoint Available" }
    @driver.save_screenshot "intial-#{formattedTime}.png"
    dropdown = @driver.find_element(:id, "RPC-Endpoint")
    begin
      dropdown.find_element(:xpath, "//option[. = 'https://api.waxsweden.org']").click
    rescue Error::NoSuchElementError
      dropdown.find_element(:xpath, "//option[. = 'https://api.wax.greeneosio.com']").click
    end

    # begin
    @driver.find_element(:css, ".login-button").click
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, ".login-modal-button") }
    @driver.save_screenshot "select-wallet-#{formattedTime}.png"
    # rescue Timeout::Error
    #   retry
    # end

    #Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.login-modal-container').present? }
    #@driver.find_element(:css, ".login-modal-button").click
    element = @driver.find_element(:css, ".login-modal-button")
    @driver.execute_script("arguments[0].click();", element)
    #root > div > div > div:nth-child(2) > div.login-modal-container > button:nth-child(2)
    @driver.save_screenshot "wallet-selected-#{formattedTime}.png"

    #Wood
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, ".info-title-name").displayed? }
    Selenium::WebDriver::Wait.new(timeout: 90).until { @driver.find_element(:css, ".card-container--time").text == "00:00:00" }
    expect(@driver.find_element(:css, ".card-container--time").text).to eq("00:00:00")
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, ".tooltip:nth-child(1) .plain-button").displayed? }
    @driver.find_element(:css, ".tooltip:nth-child(1) .plain-button").click
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, ".modal-content").displayed? }
    @driver.find_element(:css, ".short").click
    @driver.save_screenshot "wood-mined-#{formattedTime}.png"

    #Food
    @driver.find_element(:css, ".satellite__card-time").click
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, ".info-title-name").text == "Fishing Rod" }
    @driver.find_element(:css, ".tooltip:nth-child(1) .plain-button").click
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, ".modal-content").displayed? }
    @driver.find_element(:css, ".short").click
    @driver.save_screenshot "food-mined-#{formattedTime}.png"
  end
end

#Run command
#sudo /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome -headless -remote-debugging-port=8280 --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36" www.google.com

# /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222&
